// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Create a new SatisflowEngine instance.
/// This is the entry point for the Flutter app to get an engine handle.
Future<SatisflowEngine> newEngine() => RustLib.instance.api.crateApiNewEngine();

/// Get engine version string for debugging purposes.
Future<String> ffiEngineVersion() =>
    RustLib.instance.api.crateApiFfiEngineVersion();

/// Create a new factory and return its ID as a String.
Future<FfiResultString> ffiCreateFactory({
  required SatisflowEngine engine,
  required String name,
  String? description,
}) => RustLib.instance.api.crateApiFfiCreateFactory(
  engine: engine,
  name: name,
  description: description,
);

/// Get a factory by ID, returning a cloned Factory if found.
Future<Factory?> ffiGetFactory({
  required SatisflowEngine engine,
  required String id,
}) => RustLib.instance.api.crateApiFfiGetFactory(engine: engine, id: id);

/// Get all factories as a HashMap with String keys (UUIDs converted).
Future<Map<String, Factory>> ffiGetAllFactories({
  required SatisflowEngine engine,
}) => RustLib.instance.api.crateApiFfiGetAllFactories(engine: engine);

/// Delete a factory by ID.
Future<FfiResult> ffiDeleteFactory({
  required SatisflowEngine engine,
  required String id,
}) => RustLib.instance.api.crateApiFfiDeleteFactory(engine: engine, id: id);

/// Create a logistics line between two factories and return the new line's ID.
Future<FfiResultString> ffiCreateLogisticsLine({
  required SatisflowEngine engine,
  required String fromId,
  required String toId,
  required TransportType transportType,
  required String transportDetail,
}) => RustLib.instance.api.crateApiFfiCreateLogisticsLine(
  engine: engine,
  fromId: fromId,
  toId: toId,
  transportType: transportType,
  transportDetail: transportDetail,
);

/// Update an existing logistics line.
Future<FfiResult> ffiUpdateLogisticsLine({
  required SatisflowEngine engine,
  required String id,
  required String fromId,
  required String toId,
  required TransportType transportType,
  required String transportDetail,
}) => RustLib.instance.api.crateApiFfiUpdateLogisticsLine(
  engine: engine,
  id: id,
  fromId: fromId,
  toId: toId,
  transportType: transportType,
  transportDetail: transportDetail,
);

/// Get a logistics line by ID, returning a cloned LogisticsFlux if found.
Future<LogisticsFlux?> ffiGetLogisticsLine({
  required SatisflowEngine engine,
  required String id,
}) => RustLib.instance.api.crateApiFfiGetLogisticsLine(engine: engine, id: id);

/// Get all logistics lines as a HashMap with String keys.
Future<Map<String, LogisticsFlux>> ffiGetAllLogistics({
  required SatisflowEngine engine,
}) => RustLib.instance.api.crateApiFfiGetAllLogistics(engine: engine);

/// Get transport type as a string for a given logistics line.
Future<String> ffiGetLogisticsTransportType({required LogisticsFlux flux}) =>
    RustLib.instance.api.crateApiFfiGetLogisticsTransportType(flux: flux);

/// Get all logistics transport types as a HashMap with String keys.
Future<Map<String, String>> ffiGetAllLogisticsTransportTypes({
  required SatisflowEngine engine,
}) => RustLib.instance.api.crateApiFfiGetAllLogisticsTransportTypes(
  engine: engine,
);

/// Delete a logistics line by ID.
Future<FfiResult> ffiDeleteLogisticsLine({
  required SatisflowEngine engine,
  required String id,
}) =>
    RustLib.instance.api.crateApiFfiDeleteLogisticsLine(engine: engine, id: id);

/// Create a TransportType from a type name string.
/// This is needed because TransportType is opaque in Flutter and cannot be constructed directly.
Future<TransportType> ffiCreateTransportType({required String typeName}) =>
    RustLib.instance.api.crateApiFfiCreateTransportType(typeName: typeName);

/// Reset the engine to an empty state.
Future<FfiResult> ffiReset({required SatisflowEngine engine}) =>
    RustLib.instance.api.crateApiFfiReset(engine: engine);

/// Get global power statistics for all factories.
Future<PowerStats> ffiGlobalPowerStats({required SatisflowEngine engine}) =>
    RustLib.instance.api.crateApiFfiGlobalPowerStats(engine: engine);

/// Run one update cycle and return global item balances.
Future<Map<String, double>> ffiUpdate({required SatisflowEngine engine}) =>
    RustLib.instance.api.crateApiFfiUpdate(engine: engine);

/// Add a blueprint template and return its ID as a String.
Future<String> ffiAddBlueprintTemplate({
  required SatisflowEngine engine,
  required ProductionLineBlueprint blueprint,
}) => RustLib.instance.api.crateApiFfiAddBlueprintTemplate(
  engine: engine,
  blueprint: blueprint,
);

/// Get a blueprint template by ID.
Future<ProductionLineBlueprint?> ffiGetBlueprintTemplate({
  required SatisflowEngine engine,
  required String id,
}) => RustLib.instance.api.crateApiFfiGetBlueprintTemplate(
  engine: engine,
  id: id,
);

/// Get all blueprint templates as a HashMap with String keys.
Future<Map<String, ProductionLineBlueprint>> ffiGetAllBlueprintTemplates({
  required SatisflowEngine engine,
}) => RustLib.instance.api.crateApiFfiGetAllBlueprintTemplates(engine: engine);

/// Remove a blueprint template by ID.
Future<FfiResult> ffiRemoveBlueprintTemplate({
  required SatisflowEngine engine,
  required String id,
}) => RustLib.instance.api.crateApiFfiRemoveBlueprintTemplate(
  engine: engine,
  id: id,
);

/// Update a blueprint template's name and description.
Future<FfiResult> ffiUpdateBlueprintTemplate({
  required SatisflowEngine engine,
  required String id,
  required String name,
  required String description,
}) => RustLib.instance.api.crateApiFfiUpdateBlueprintTemplate(
  engine: engine,
  id: id,
  name: name,
  description: description,
);

/// Instantiate a blueprint template into a factory.
Future<FfiResultStringString> ffiInstantiateBlueprintIntoFactory({
  required SatisflowEngine engine,
  required String factoryIdStr,
  required String blueprintIdStr,
  String? customName,
}) => RustLib.instance.api.crateApiFfiInstantiateBlueprintIntoFactory(
  engine: engine,
  factoryIdStr: factoryIdStr,
  blueprintIdStr: blueprintIdStr,
  customName: customName,
);

/// Save the engine state to a JSON string.
/// Throws an exception on error (no opaque wrapper).
Future<String> ffiSaveToJson({required SatisflowEngine engine}) =>
    RustLib.instance.api.crateApiFfiSaveToJson(engine: engine);

/// Load the engine state from a JSON string.
/// Throws an exception on error.
Future<void> ffiLoadFromJson({
  required SatisflowEngine engine,
  required String json,
}) => RustLib.instance.api.crateApiFfiLoadFromJson(engine: engine, json: json);

/// Serialize a blueprint template to a JSON string for export.
/// Throws an exception on error.
Future<String> ffiBlueprintToJson({
  required ProductionLineBlueprint blueprint,
}) => RustLib.instance.api.crateApiFfiBlueprintToJson(blueprint: blueprint);

/// Deserialize a blueprint template from a JSON string for import.
/// Throws an exception on error.
Future<ProductionLineBlueprint> ffiBlueprintFromJson({required String json}) =>
    RustLib.instance.api.crateApiFfiBlueprintFromJson(json: json);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Factory>>
abstract class Factory implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FfiResult < () >>>
abstract class FfiResult implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FfiResult < String >>>
abstract class FfiResultString implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FfiResult < (String , String) >>>
abstract class FfiResultStringString implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LogisticsFlux>>
abstract class LogisticsFlux implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PowerStats>>
abstract class PowerStats implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ProductionLineBlueprint>>
abstract class ProductionLineBlueprint implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner< SatisflowEngine>>
abstract class SatisflowEngine implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TransportType>>
abstract class TransportType implements RustOpaqueInterface {}
